kind: pipeline
name: default

workspace:
  base: /packadd
  path: src/github.com/antoinedray/vim-packadd

steps:
- name: build
  image: python:latest
  commands:
  - python3 --version
  - pip3 install setuptools
  - python3 setup.py sdist

- name: install
  image: python:latest
  commands:
  - python3 --version
  - pip3 install setuptools
  - python3 setup.py install --user

- name: test
  image: python:latest
  commands:
  - python3 --version
  - pip3 install setuptools
  - python3 setup.py install --user
  - test/test.sh

- name: deploy
  image: python:latest
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
  - python3 --version
  - pip3 install setuptools
  - pip3 install twine
  - python3 setup.py sdist
  - ls dist
  - twine upload $(ls dist/*.tar.gz) -u $USERNAME -p $PASSWORD
  when:
    branch:
    - master