kind: pipeline
name: default

platform:
  os: linux
  arch: arm

workspace:
  base: /packadd
  path: src/github.com/antoinedray/vim-packadd

steps:
- name: build
  image: python:latest
  commands:
  - python3 setup.py sdist

- name: default install
  image: python:latest
  commands:
  - python3 setup.py install --user
  - export PY_USER_BIN=$(python -c 'import site; print(site.USER_BASE + "/bin")')
  - export PATH=$PY_USER_BIN:$PATH
  - packadd --version

- name: epita install
  image: python:latest
  commands:
  - python3 setup.py epita_install -a
  - /bin/bash -c 'source ~/.bashrc'
  - packadd --version

- name: test'
  image: python:latest
  commands:
  - python3 setup.py test

- name: lint
  image: python:latest
  commands:
  - pip3 install flake8
  - flake8 packadd/ epita/

- name: deploy
  image: python:latest
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
  - pip3 install twine
  - python3 setup.py sdist
  - twine upload $(ls dist/*.tar.gz) -u $USERNAME -p $PASSWORD
  when:
    branch:
    - master