kind: pipeline
name: default

workspace:
  base: /packadd
  path: src/github.com/antoinedray/vim-packadd

steps:
- name: build
  image: python:latest
  commands:
  - python setup.py sdist

- name: deploy
  image: python:latest
  commands:
  - pip install twine
  - twine upload dist/vim-packadd-0.3.7.tar.gz