kind: pipeline

steps:
- name: build source
  image: python:latest
  commands:
  - python setup.py sdist

- name: deploy
  image: python:latest
  commands:
  - pip install twine
  - twine upload dist/vim-packadd-0.3.7.tar.gz