kind: pipeline
name: default

platform:
  os: linux
  arch: arm

workspace:
  base: /packadd
  path: src/github.com/antoinedray/vim-packadd

steps:
- name: build
  image: python:latest
  commands:
  - python3 setup.py sdist

- name: default install
  image: python:latest
  commands:
  - python3 setup.py install --user
  - export PY_USER_BIN=$(python -c 'import site; print(site.USER_BASE + "/bin")')
  - export PATH=$PY_USER_BIN:$PATH
  - packadd --version

- name: epita install
  image: python:latest
  commands:
  - python3 setup.py epita_install -a
  - export PATH=/root/.local/bin:$PATH
  - python3 ~/afs/.pip/bind.py packadd --version

- name: test
  image: python:latest
  commands:
  - python3 setup.py test

- name: lint
  image: python:latest
  commands:
  - pip3 install flake8
  - flake8 packadd/ epita/